# 项目相关配置
zg:
  # 名称
  name: ZhiGe
  # 版本
  version: 4.7.3
  # 版权年份
  copyrightYear: 2021
  # 是否指定任意目录
  appointProfile: false
  # 储存相关根目录
  profile: .zg
  # 获取ip地址开关
  addressEnabled: false
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8090
  servlet:
    # 应用的访问路径
    context-path: /
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100
 
# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn
    com.oly: debug 
# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
    prefix: classpath:/templates/
    template-resolver-order: 1
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: prod
    group: 
      "prod": "prodMybatis,prodFlyway"
  # 文件上传
  servlet:
     multipart:
      # 文件上传开关默认 true
       enabled: true
       # 文件延迟解析默认 false
       resolve-lazily: false
       # 文件写入磁盘阙值默认 0 
       file-size-threshold: 0
       # 临时目录
       location: ${tmp_path}
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
      
      
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache/ehcache-shiro.xml
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 管理地址
    adminUrl: /admin
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain: 
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
    # 设置密钥，务必保持唯一性（生成方式，直接拷贝到main运行即可）Base64.encodeToString(CipherUtils.generateNewKey(128, "AES").getEncoded()) （默认启动生成随机秘钥，随机秘钥会导致之前客户端RememberMe Cookie无效，如设置固定秘钥RememberMe Cookie则有效）
    cipherKey: 
  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: -1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false
  rememberMe:
    # 是否开启记住我
    enabled: true

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*,/cms/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
